### ISSUE TITLE
Server responded with error code 503.

### ISSUE THREAD

**Issue by qustavo** [Narrat/translate#12]
It's happening randomly, no idea why

**Comment by Narrat** [comment]
Locally I cannot reproduce this.

Is this error linked to specific words or characters? Like you try word a and it errors, then try b and it works and back to a and it errors out again?

**Comment by lenosi** [comment]
I have this problem too. I don't know why. Maybe Google block this after many reply for translate?

**Comment by qustavo** [comment]
I think it's an API rate restriction

On Mon, Dec 21, 2015 at 2:48 PM, eNKeyS notifications@github.com wrote:

> I have this problem too. I don't know why. Maybe Google block this after
> many reply for translate?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Narrat/translate/issues/12#issuecomment-166309311.

## 

Gustavo Chaín Dumit

**Comment by AlexTalker** [comment]
@Narrat Since I have the same problem, I've added simple debug line, and I've got that 503 might be result of unusual traffic from user network.
![2016-01-15-014951_1366x768_scrot](https://cloud.githubusercontent.com/assets/3531127/12340180/475069fa-bb2a-11e5-8a0b-599e72e55e82.png)

**Comment by AlexTalker** [comment]
@Narrat btw, this was first time I run the software so I have no idea why 503 could be achieved.(No other software except browser(rarely) is using google services on my system)

**Comment by Narrat** [comment]
Ok, now we got something.
using ru produces the message.
Although I don't know what's the cause of it. Does ru work sometimes or does it fail everytime?

@gchaincl, @enkeys: Same language identifier or different one?

**Comment by Narrat** [comment]
I found something on this topic.
So propably fixable, but I need to read further into the specific topic. So no quick fix for now

Edit: Just to mention it.
The need and validation of access tokens could cause this.

**Comment by AlexTalker** [comment]
@Narrat maybe.
Thank you for response. BTW, now looks like software works. Seems like temporary but annoying problem.

**Comment by qustavo** [comment]
what I've found, is that this happen at my office but not at home, which suggest it can be some google rate policy

**Comment by Narrat** [comment]
Ha.. I was kinda against adding all the stuff which should it make work flawless again, since the blocking is more or less just for a short time.
But now dunno about that. Just looked 4 words up and after that 503.
Which is kinda annoying

**Comment by mirkojovanovic** [comment]
Happens every time for me :(

**Comment by whoizit** [comment]
same for me en to ru

**Comment by Narrat** [comment]
Program itself not working anymore and I don't intend to fix this.
But do not fret, there are working alternatives out there ;)
